steps:
  # build frontend
  - name: node:10.15.1
    id: Npm install
    entrypoint: npm
    args: ['--prefix', './fe/', 'install']

  - name: node:10.15.1
    id: Test fe-project
    entrypoint: npm
    args: ['--prefix', './fe/', 'run', 'test:unit']

  - name: 'gcr.io/cloud-builders/docker'
    id: Build fe docker-image
    args: ['build', '-t', 'gcr.io/create-a-code-snippet/fe:latest', './fe/']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push fe docker-image to registry
    args: ['push', 'gcr.io/create-a-code-snippet/fe:latest']


  # build backend
  - name: 'gcr.io/cloud-builders/mvn'
    id: Test be-project
    args: ['-f', 'be/pom.xml', 'clean', 'package', '-D"spring-boot.run.profiles"=gcp']

  - name: 'gcr.io/cloud-builders/docker'
    id: Build be docker-image
    args: ['build', '-t', 'gcr.io/create-a-code-snippet/be:latest', './be/']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push be docker-image to registry
    args: ['push', 'gcr.io/create-a-code-snippet/be:latest']

timeout: '1600s'
